### ISSUE TITLE
What properties are used with which classes?

### ISSUE THREAD

**Issue by iherman** [w3c/poe#128]
The definitions of classes, more exactly the properties used on those classes, along the two documents (model and vocab) is not in sync. This makes reading the documents a bit difficult...

I have checked only the `Policy` class in more details:

1. The UML diagram in the model suggests that the allowed properties on that class are `uid`, `type`, `conflict`, `undefined`, `inheritAllowed`, and `profile`. By virtue of being a subclass of `Asset` it can also use `scope`, and via some UML tricks (that I do not really understand) the `inheritFrom` also appears.
2. The definition [in the text](https://w3c.github.io/poe/model/#h-policy) lists the first group, but does not refer to `scope`. O.k., that is still fine, but the fact that `inheritFrom` does not appear here bothers me.
3. The examples in the model document use the `@id` term which, I would think, corresponds to the `uid` by virtue of the JSON-LD encoding, and to `@type` for `type`. This is mentioned in a Note but I have not seen it clearly documented that the general terms map to these and these features of RDF. This is important to make the serialization in other syntaxes clear.
4. The examples in the model document also use properties like `permission` or `prohibition`. This comes out of the blue for the reader; of course, one can understand that these refer to a `Permission` or `Prohibition`, respectively, but on the spec level that isn't o.k.
5. One can then look at the [Definition in the vocab document](https://w3c.github.io/poe/vocab/#h-term-policy). The definition lists  	`conflict`, `inheritAllowed`, `inheritFrom`, `permission`, `profile`, `prohibition`, `undefined`. Note that `permission` and `prohibition` is present, which is good. It does not explicitly refer to `uid` and `type` because those are RDF notions anyway; see above. Note the presence of `inheritFrom` which is fine.
6. But then... the examples include properties like `assigner`, `action`, `target`, and probably others, that are not listed anywhere.

(I have not checked the other classes but there may be similar issues...)

There are too many places defining properties and it is not clear which is the authoritative one. To be perfectly honest, the UML diagram does not really talk to me, and I just see it as an extra source of possible problems. But if we choose to keep it, things should be in sync... 

I wonder whether it would not make it easier to the reader if we placed a link to the relevant entry in the vocab document for each class (e.g., a link to 4.1.1. in the vocab from 3.1 in the model). The latter should also include the 'assigner', etc., if we want to keep them really (I am not 100% sure, it may be cleaner to use only expanded rules...). The vocab document should be the authoritative definition.

**Comment by riannella** [comment]
I think (as discussed in #124) we need to put less emphasis on UML as a driver of the IM. I have a proposed update for the IM Figure (which is just a diagram now ;-) and includes names on the links between the entities.
![odrl-model](https://cloud.githubusercontent.com/assets/13191615/25258673/5e7c7a6c-2684-11e7-9cd9-95e43f281745.png)

**Comment by riannella** [comment]
Comments on:

1) There was previous concern that Asset was the parent of Policy, so I suggest we remove that relationship.

2) This means that Policy does not have a "scope" which is better.

3) Do you think we need to add more details to the Note in Section 3.1 (remember that in XML, we actually have attributes called uid and type)

4) hopefully the new figure will work

5) Should we add uid and type to the ontology and say to use rdf:about in the RDF section (for example)?

6) hopefully clearer now in the proposed disagram

RE: linking between the IM and the Vocab - do you propose that for every term in the IM (that has a definition in the Vocab) that we href that text string?

**Comment by riannella** [comment]
Here is an updated figure
![odrl-model](https://cloud.githubusercontent.com/assets/13191615/25266380/4d4b76aa-26b4-11e7-9294-916a75e69d94.png)

**Comment by iherman** [comment]
That is certainly cleaner. But not all the arrows are labelled, ie, that must be complete. Also, I would prefer all colourful blocks to represent only classes; looking at the vocabulary 'Relation' is a property (and 'Role', too?) which is an extra complication with the diagram.

**Comment by simonstey** [comment]
- move `uid` from Duty up to Rule
- add `uid` to Action/Constraint
- remove  Relation/Role concept thingy

also: the figure suggests that one can relate policies to duties, while ODRL allows to define duties for permissions only.

**Comment by riannella** [comment]
Ok, please see the attached.
@iherman I think we need the two colour boxes to show the core properties of each Class (yes, I know its not RDFy and more UMLy ;-)

![odrl-model](https://cloud.githubusercontent.com/assets/13191615/25322475/ce9e0e8c-28fa-11e7-89b4-af666f751b71.png)

**Comment by riannella** [comment]
And we will rename attribute to property ;-)

**Comment by iherman** [comment]
I am fine with the diagram I think. Personally, I would prefer to make it more black-green-white rather than these black-yellow colours, but that is really a matter of taste...

**Comment by riannella** [comment]
See attached?
![odrl-model](https://cloud.githubusercontent.com/assets/13191615/25413438/a1b00398-2a6d-11e7-864a-019816b0e2fe.png)

**Comment by iherman** [comment]
Why not use `type` instead of `isA`?

**Comment by riannella** [comment]
Would that get it confused with the "type" in Policy?

**Comment by iherman** [comment]
I take your point. Leave it as is, and see if the readers complain...

**Comment by riannella** [comment]
or "typeOf" ?

**Comment by iherman** [comment]
Either... technically it is subclass of, right? But that is too technical at that level.

Leave it as is. There are other things to worry about:-)

**Comment by riannella** [comment]
Yes, they are subclasses of Rule.

**Comment by vroddon** [comment]
It is a beautiful figure. But I would have chosen colours with more constrast, so that even if printed b/w the model is well rendered. 

I am sorry to insist, but I can foresee this figure being reproduced many times, in many presentation and in many printed papers. So I believe that the effort worths. 

For example, a couple of years ago I prepared a "ODRL reference card". It is still online:
http://www.lider-project.eu/sites/default/files/referencecards/Licensing-ODRL-reference-card-v3.pdf

The figure will go in to-be-printed documents like that.

Final thought: some day the W3C should publish an official colour code&style for these things.

**Comment by iherman** [comment]
@vroddon there is no 'official' colour code guide, although there some issues mentioned in [1]. However, the issue is often the requirement on minimum luminosity and the right contrast among colours. The requirements are listed in the WAI document[2] but, probably, the tools advising on on the right contrasts are easier to use. [3] is a good tool that can be installed on your machine, [4] looks like a great online tool.


1. https://w3c.github.io/manual-of-style/
2. https://www.w3.org/WAI/WCAG20/quickref/#visual-audio-contrast-contrast
3. https://www.paciellogroup.com/resources/contrastanalyser/
4. http://contrast-finder.tanaguru.com/

**Comment by riannella** [comment]
I have created a plainer version - see attached 
(also I have removed "name" from Action as that is an XML-thing)
![odrl-model](https://cloud.githubusercontent.com/assets/13191615/25463022/893100f0-2b36-11e7-8b0e-9245870e2a16.png)

**Comment by riannella** [comment]
Note: action does not have a uid property

**Comment by larsgsvensson** [comment]
> Note: action does not have a uid property

According to the [ED of the vocab document](https://w3c.github.io/poe/vocab/#term-Rule), nor does `Rule`. I also note that `Rule` (as an abstract class) is not defined in the Information Model

**Comment by riannella** [comment]
I have updated the IM based on the new figure (class/property view) and removed the UML stuff.
I have also added a "Rule" section to the document- as the parent of properties for Perm/Prohib/Duty.

Please review the diffs here: https://github.com/w3c/poe/commit/e055b79b52922eb52942a7622cebe25df3c091f1

**Comment by simonstey** [comment]
for some reason my comments didn't get through ;(

> Yes, they are subclasses of Rule.

Thus, they *all* (incl. Duty) inherit *all* features from Rule. 
As such, a policy like:

```turtle
:policy1 a odrl:Policy;
  odrl:permission :per1 ;
  odrl:prohibition :pro1 ;
  odrl:prohibition :duty1 .
  odrl:permission :duty1 .

:per1 a odrl:Permission .
:pro1 a odrl:Prohibition .
:duty1 a odrl:Duty .
```

is a valid policy according to the latest IM diagram.

So either:

1. We remove the relationship between Policy and Rule, and add ones between Policy and Perm/Prohib.
2. Allow Policies to directly reference Duties via `odrl:duty` (my preference)

**Comment by larsgsvensson** [comment]
Renato,

Thanks for the updated model. Some minor comments:

Line 106: "The ODRL Information Model represents Policies to express Permissions and Prohibitions related to the usage of Assets." Suggestion: "The ODRL Information Model represents Policies that express Permissions, Prohibitions and Duties related to the usage of Assets."

Line 821: This one seems to be left in there by accident...

Line 831: Current text "For a Rule to become effective, it MUST be valid (ie it's constraints are satisfied)." Suggestion: "For a Rule to become effective, it MUST be valid (ie all it's constraints MUST be satisfied)."

Line 845: similar to line 831

Line 874: similar to line 831

Line 872: Current text: "A Prohibition class is a specific type of Rule that specifies the Actions that MUST NOT be <strong>permitted</strong> to be performed on an Asset." Suggestion: "A Prohibition class is a specific type of Rule that specifies the Actions that the Assignee MUST NOT perform on an Asset." The Prohibition already says that they are not permitted so you cannot prohibit the Actions once again...

Line 1002: Current text: "Constraints MUST be checked by ODRL Processors  at the time of executing the relevant action." Suggestion: "ODRL Processors MUST check all constraints at the time of executing the relevant Action." (Is a minor nitpick but in normative language we should always prefer active form over passive...).

And regarding @simonstey 's comment:

>  So either:
> 1.    We remove the relationship between Policy and Rule, and add ones between Policy and Perm/Prohib.
> 1.   Allow Policies to directly reference Duties via odrl:duty (my preference)

I daresay that I quite like the model in the [new diagram](https://github.com/w3c/poe/blob/e055b79b52922eb52942a7622cebe25df3c091f1/model/fig/00Model.png) where the `Policy` only can specify `Permission`s and `Prohibition`s and the `Dutie`s are related to the `Permission`s since that makes it clear that the `Permission` is only granted when the `Duty` has been fulfilled.

**Comment by riannella** [comment]
@larsgsvensson Thanks. Made those updates. Except for line 872, did not include "that the Assignee" as we include parties in the Rule narrative.

**Comment by riannella** [comment]
@simonstey Yes, you are correct that it is a "valid policy according to the latest IM diagram" but it is not valid according to the IM narrative:
  "A Duty must only be associated with a Permission"

The ODRL Ontology has defined prohibition property with range owl:unionOf ( :Prohibition  :Action ) 
Maybe we should also add disjointWith classes?

Or are you saying we should support Polices with just Duties ?
(and what would that mean?)

**Comment by larsgsvensson** [comment]
Thanks, @riannella . Is that commit https://github.com/w3c/poe/commit/30eabde4d832bdfe0a131adda3a3f3e0b52d0455 ?

**Comment by riannella** [comment]
@larsgsvensson Yes

**Comment by riannella** [comment]
Any final comments/feedback on this issue??

**Comment by simonstey** [comment]
> Any final comments/feedback on this issue?

adapt figure wrt. #154
