### ISSUE TITLE
Definition of relations (model)

### ISSUE THREAD

**Issue by iherman** [w3c/poe#135]
3.2.1 defines relations. It refers to an `Entity` (whatever that means), but the text is not very clear how that is used. It also says

> The default value for the relation attribute is target which indicates

which is again unclear; because `value` is often used to denote the "object" in RDF (or as part of a key-value pair in JSON), one would expect to use something like

```json
   {
     "relation" : "target"
   }
```

but that is clearly wrong.

The vocab document makes it clearer. "relation" is a property, but it is "abstract", ie, it is used in ODRL via its subproperties. "target" is one of those, "output" is another.

This is an example where the model document, by itself, confusing, and needs re-write. Make the subproperty feature explicit in the model.

(I believe the usage of the term "Entity" is the main reason for the confusion. A UML term creeping in?)

**Comment by riannella** [comment]
Yes, "default value" is not the best wording (now).
I will update this to reflect its role as and abstract property as well.

There are too many "entity" words...I think because we used definite "The" instead of the indefinite "A", such as "The Duty entity may..." 

Perhaps we can simply replace all these (and have "A Duty may..." ?

**Comment by simonstey** [comment]
> Perhaps we can simply replace all these (and have "A Duty may..." ?

+1

(IIRC I complained about that in another issue too)

**Comment by simonstey** [comment]
found that other issue -> #104

**Comment by riannella** [comment]
Removed "entity" throughout the document.
