### ISSUE TITLE
Undefined Actions - deprecate?

### ISSUE THREAD

**Issue by riannella** [w3c/poe#139]
Should we deprecate the Undefined Actions section:
  https://w3c.github.io/poe/model/#undefined

It makes little sense under the "open world assumption" and is typically implementor (or Profile) dependent.

**Comment by simonstey** [comment]
+1

**Comment by riannella** [comment]
WG agreed (8 May) to remove this section and deprecate terms in Vocab

**Comment by riannella** [comment]
Removed the Undefined Actions section from IM and deprecated in the Vocab and removed from encodings

Commit 01a3a9aa29476308b90423457c635c745a09938f

**Comment by aisaac** [comment]
Is the resolution suggesting to remove the possibility of any new actions, even following the mechanisms suggested in #160?
If not then it should be explicit here that a resolution to #160 should follow up on closing #139

Also is the resolution suggesting that there is nothing to replace the processing options  (support, ignore, invalid) at https://www.w3.org/TR/2017/WD-odrl-model-20170223/#undefined.
I'm not asking for this feature myself. Just curious because it's not very clearly noted in this issue.

**Comment by riannella** [comment]
We state at: https://w3c.github.io/poe/model/#action
"The ODRL Vocabulary [vocab-odrl] defines a standard set of common Actions that may be used and ODRL Profiles may also define Actions"

If (and only if) we remove Profiles, then we would make it clear that terms can still be used from different vocabs in ODRL.

Correct, there is nothing replacing the deprecated Undefined terms.

**Comment by aisaac** [comment]
OK then what I'm asking for is that Profiles would point to a mechanism to extend actions in a way that is still beneficial to interoperability across profiles, which is what the Web Annotation pattern for motivations tries to achieve for a different set of concepts. If this is the idea you have, you record it and #160 not discarded then I'm more than happy :-)
