### ISSUE TITLE
odrl:use

### ISSUE THREAD

**Issue by riannella** [w3c/poe#140]
Should we mention odrl:use in the Information Model as the top of the hierarchy of all actions?
(and must be supported??)

**Comment by vroddon** [comment]
Please note that the current text about Actions does not say anything about hierarchies.
http://w3c.github.io/poe/model/#action

**Comment by riannella** [comment]
Should we add it??

**Comment by vroddon** [comment]
I am strongly in favour of it. I think we need a something to meed "everything", for the two examples that I provide next:

**First example: All rights reserved.**
```
<http://purl.org/NET/rdflicense/allrightsreserved>  
  a	odrl:Policy ;
  rdfs:label   "All rights reserved"@en;
  dct:publisher " None" ;
  rdfs:comment "This license does not disclose any of the IPR and database rights"@en ;
  cc:legalcode <http://en.wikipedia.org/wiki/All_rights_reserved> ;
  odrl:prohibition [
    odrl:action ldr:IPRRight, ldr:databaseRight;
] . 	
```

I was more precise and I distinguished between copyright and database right, also limiting the prohibition in a very specific manner. odrl:use is not precise because the asset can still be read if it is in the internet for example: we only forbid copyright-protected actions like "distribute" o "copy". 

For completitude, this is the opposite example: 
**Second example: something is in the public domain**
Please note again that by using  ldr:IPRRight, ldr:databaseRight the actions permitted are very clear. I still cannot use the resource to commit defamation. 
Thus...
.... I am in favour in declaring odrl:use
.... I would even declare two actions for odrl:IPRight and odrl:databaseRight (but without declaring further hierarchies, as this is jurisdiction dependant). I would define databaseRight using  CreativeCommons's formula: "database rights, wherever they exist".

```
<http://purl.org/NET/rdflicense/publicdomain>
  a       odrl:Policy ;
  rdfs:label   "Public domain";
  dct:publisher " None" ;
  cc:legalcode <http://en.wikipedia.org/wiki/Public_domain> ;
  rdfs:comment "This statement can be applied to material truly in the public domain (because rights have expired, forfeited or are innaplicable)." ;
  odrl:permission [
  odrl:action ldr:IPRRight, ldr:databaseRight;
] . 	 
```

**Comment by riannella** [comment]
We will probably need a more refined definition for odrl:use than "The Assigner permits/prohibits the Assignee to use the Asset as agreed"

**Comment by riannella** [comment]
Are you proposing to add odrl:IPRight and odrl:databaseRight to the Vocab?

What would be their definitions?

**Comment by vroddon** [comment]
@riannella I would pay attention to CreativeCommons 4.0 for one reason: they have no jurisdiction-dependant ports and they aim at being universal. Slightly changing the text at https://creativecommons.org/licenses/by/4.0/legalcode we could have:

> **IPRight** - copyright and/or similar rights closely related to copyright including, without limitation, performance, broadcast and sound recording without regard to how the rights are labeled or categorized
> 
> **databaseRight** - rights other than copyright resulting from Directive 96/9/EC of the European Parliament and of the Council of 11 March 1996 on the legal protection of databases, as amended and/or succeeded, as well as other essentially equivalent rights anywhere in the world.

**Comment by riannella** [comment]
@vroddon the CC4 definition of "IPRight" includes database rights?
(and the current definition only applies to EU jurisdictions, which we cannot support ;-(

I am slightly confused on what the proposed action hierarchy is (or should be).

At the moment, we have odrl:use and odrl:transfer at the "top".

**Comment by vroddon** [comment]
Yes, the CC definition of "Copyright and Similar Rights" includes that of database rights. I have split them on purpose, but we can keep only one single term. 

But I do not agree with the "jurisdiction problem": as it is formulated, the CC's definitions are clear and jurisdiction-agnostic. The text "as well as other essentially equivalent rights anywhere in the world" is very clear.
There is also a reference that explicitly excludes "Patent and trademark rights" as well as moral rights; that I have dropped. 

Still, the stronger point of CC's text is that it is universal and well known: if we use it there will be little ambiguity (or at least no more than in CC's texts).

**Comment by riannella** [comment]
@vroddon You can't define databaseRights in terms of EU laws and say that is jurisdiction-free. Australia (and many other countries) would disagree ;-)

But..my underlying question is that I can't see these term(s) as **actions**? ie verbs?
What are we allowing the assignee to do/not do?

**Comment by riannella** [comment]
As discussed at the F2F and #182 - we only add use and transfer to the IM.
