### ISSUE TITLE
Note on Duty

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/poe#149]
The note on [Duty](https://w3c.github.io/poe/vocab/#term-Duty) says

> While implying different semantics, the Duty entity is similar to Permission in that it is an Action that must be undertaken.

To me that feels incorrect. If I have the permission to do something I am still not obliged to do it (i. e. the performing of a Persmission is optional). In other words: A Duty is a Rule that **must** be performed by the Assignee. A Permission is a Rule that **may** be performed by the Assignee.

**Comment by riannella** [comment]
Updated in this commit e055b79b52922eb52942a7622cebe25df3c091f1

**Comment by simonstey** [comment]
> To me that feels incorrect. If I have the permission to do something I am still not obliged to do it (i. e. the performing of a Permission is optional). In other words: A Duty is a Rule that must be performed by the Assignee. A Permission is a Rule that may be performed by the Assignee.

I would even argue that the same holds for Duties too:

> A Duty class is a specific type of Rule that specifies agreed Actions that are obligatory and MUST be fulfilled. **A Duty is only associated with a Permission.** 

Since Duties can only be associated with Permissions, I only have to fulfill a Duty if I want to be eligible for its respective Permission. (I don't have to pay you 100000€ if I don't want to use your data ;)

**Comment by riannella** [comment]
Proposal: Update first para of Duty section to read:

A Duty class is a specific type of Rule that specifies agreed Actions that are <strong>obligatory</strong> and MUST be fulfilled **in order to be granted the associated Permission.** A Duty **MUST** only associated with a Permission. The Permission is valid (including the Permission's constraints all being satisfied) if and only if the Duty has been fulfilled. The Duty class inherits all the properties from the Rule class.

**Comment by riannella** [comment]
Change made

commit 54054796c0e88bca9a7f9e2ca12a322ff4ac34bd

**Comment by larsgsvensson** [comment]
Yes, that answers my issue.

Thanks,

Lars
