### ISSUE TITLE
Question about Data Quality Vocabulary  case

### ISSUE THREAD

**Issue by riannella** [w3c/poe#159]
@aisaac

Here's a small piece of feedback for POE, where I'd like to specifically add Riccardo Albertoni to the thread. We've both worked on the W3C Data Quality Vocabulary, which appears as a POE use case at
https://www.w3.org/TR/2017/WD-poe-ucr-20170223/#POE.UC.26

DQV uses ODRL for expressing a quality policy:
https://www.w3.org/TR/vocab-dqv/#ExpressConformanceWithPolicy
It seems that because of the latest changes on POE constraint language, especially the operands (http://w3c.github.io/poe/model/#constraint ), the example we've written is now wrong. Can you confirm this?

**Comment by simonstey** [comment]
@aisaac 

> It seems that because of the latest changes on POE constraint language, especially the operands (http://w3c.github.io/poe/model/#constraint ), the example we've written is now wrong. Can you confirm this?

yes, as of now it should look like this ->

```turtle
:policy1 a odrl:Offer, dqv:QualityPolicy ;
  odrl:permission [
    a odrl:Permission ;
    odrl:target :myDataset ;
    odrl:action odrl:read ;
    odrl:assigner :serviceProvider;    
    odrl:duty [
      a odrl:Duty; 
      odrl:assignee :serviceProvider;
      odrl:target :myDatasetSparqlDistribution ;
      odrl:constraint [
        a odrl:Constraint ;
        prov:wasDerivedFrom :sparqlEndpointUptime;
        odrl:leftOperand odrl:percentage ;
        odrl:operator odrl:gteq ;
        odrl:rightOperand "99"^^xsd:double ;
      ]     
    ]
  ]
```
  .

**Comment by aisaac** [comment]
Thanks @simonstey!
I'm trying to loop @riccardoAlbertoni in. I guess this should becomes an issue of DQV rather than POE. Or maybe we should postpone this until POE has progressed towards Rec status - in case there would be other changes to the POE part on constraints.

**Comment by riannella** [comment]
@aisaac Yes, probably a DQV issue now :-)

BTW, the Duty in your example does not have an action.

**Comment by aisaac** [comment]
OK this should be transferred. Hopefully the new W3C Data Exchange Working Group will accept to be the home for the issue.

But before we close I have to ask @riannella about the duty, so that we know for sure how to change DQV.
When you say "the Duty in your example does not have an action", what kind of action would be appropriate here?
The idea is that the serviceProvider would commit to a certain level of uptime. But in a way, this is rather a commitment to having a certain state persist, rather than someone doing a specific action.Does POE have something for this?

**Comment by riannella** [comment]
The duty action would be something like "uptime" (as that is what is also being constrained).
ODRL does not include this term.

We did work on this a long long time ago:
https://www.w3.org/2012/09/odrl/archive/odrl.net/Profiles/Services/WD-20080402.html

**Comment by aisaac** [comment]
Thanks.
We won't probably be able to create this as part of DQV, because that would put us in a strange position where we could potentially have to include actions for everything relevant to quality. But we can mimic one, for the sake of the example.

Do you know which standard Action we could attach it to?
To encourage best practices, we'd like to show how to mint a new action by extending existing ones, following the approach I've mentioned at #160.

By the way in case you're interested, we've done it (extending an existing Motivation in the Web Annotation model) earlier in DQV, this is what it looks like:
https://www.w3.org/TR/vocab-dqv/#dqv:qualityAssessment

**Comment by riannella** [comment]
I don't think there is a "standard" action that you can re-use.

See the Profile mechanism here: http://w3c.github.io/poe/model/#profile-requirements

**Comment by aisaac** [comment]
No standard action? OK we will have to try to do it ourselves then, trying to get inspiration from
https://www.w3.org/2012/09/odrl/archive/odrl.net/Profiles/Services/WD-20080402.html

Regarding the profile mechanism, the pattern for extending actions seems ok. But that's only the pattern. I still disagree with the use of ODRL specific properties for this. But that's the topic of #160.

So this ticket could be closed from the perspective of POE. But while it doesn't have a home for sure in another group (maybe DXWG can adopt it, but it's unclear to me now) is it possible to leave it here, saying this is not an issue for the ODRL vocabulary and IM?

**Comment by riannella** [comment]
Perhaps take this requirement to the new Dataset Exchange WG:
  https://www.w3.org/2017/dxwg/wiki/Main_Page

and propose they create a full ODRL profile to capture all the "service" requirements?

Thanks ;-)
