### ISSUE TITLE
What's the immutable core of ODRL that cannot be changed by Profiles?

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#173]
[4.2 ODRL Profile Requirements](http://w3c.github.io/poe/model/#profile-requirements)
 >The requirements for communities developing ODRL Profiles MUST document the following:
>
>    - Any additions to the Information Model
> - **Any cardinality changes to the Information Model**
> - **Any aspects of the Information Model that will have different default values or (editorial) interpretations**
> - **Any aspects of the Information Model that is not being supported**
> - New Vocabulary terms
> - **Vocabulary terms not explicitly being supported**
> - Vocabulary terms with more specific interpretations
> - The ODRL Profile identifier (IRI)

What are the "core" concepts of ODRL that cannot be changed/removed by Profiles?

**Comment by philarcher** [comment]
That looks like a set of requirements that could be taken on board by DXWG. They will be working on a UCR within the coming weeks and so, perhaps, this list can be the basis of a use case in that document?

**Comment by simonstey** [comment]
> .. perhaps, this list can be the basis of a use case in that document?

\- the bold parts, as a Profile shouldn't be a valid ODRL Profile if it throws away/alters all concepts of ODRL

**Comment by riannella** [comment]
Profile cannot change the IM

Only add terms.

review core model - all of the MUST's ok - or change to SHOULD ? 

keep only "If a consuming system does not understand the ODRL Profile, then it MAY continue processing the Policy expression, but it SHOULD NOT assume it has interpreted the Policy expression correctly"

s/"any consuming system"/"any consuming system that supports/implements given profile"/

update sections on conflict types/operators -> MUST but you can add more

**Comment by riannella** [comment]
Make it clear on the purpose of Profiles.

And they may reuse ODRL Common Vocab terms

**Comment by riannella** [comment]
I have updated the ODRL Profiles section.  Now only talks about adding terms.

Also added a "mechanism" subsection to show how to define the new terms (please review carefully @vroddon ;-)

Also added use/transfer to the Action section.

**Comment by riannella** [comment]
commit is here: 225dce9c885b31a719f71a9ea1d3f8bf49a3ec0d

**Comment by larsgsvensson** [comment]
Just out of interest: Since profile creators are encouraged to mint IRIs for their profiles, will there also be an IRI identifying that ODRL Core Profile? That would fit nicely with the profile negotiation being done in DXWG as pointed out by @philarcher1

**Comment by riannella** [comment]
I don't think so.

There is probably not a concept of a "Core Profile" in that a purpose-specific vocabulary - only the odrl core vocabulary - which are the terms you need as a foundation to  make odrl expressions...

Is there a use case for one?

**Comment by larsgsvensson** [comment]
My use case is that when we transport ODRL data using one of the common media types (e. g. application/ld+json) that doesn't tell the client which profile it will get and the client also cannot ask for ODRL information conforming to a specific profile since the generic media type cannot transport that kind of information. In the DXWG we'll develop an http extension mechanism to do that where profiles are identified by URIs. The ODRL spec says that ODRL profiles need to have URIs but it would be helpful to have a URI for the core profile, too, so that a server can tell the client that the ODRL data conforms to the core profile.

**Comment by riannella** [comment]
I see..if you are only using the "core", then can you just use the odrl namespace identifier?

**Comment by simonstey** [comment]
> The ODRL spec says that ODRL profiles need to have URIs but **it would be helpful to have a URI for the core profile, too**, so that a server can tell the client that the ODRL data conforms to the core profile.

sounds reasonable to me..

**Comment by riannella** [comment]
When would ODRL data **not** conform to the "core profile" ?

**Comment by simonstey** [comment]
> The ODRL spec says that ODRL profiles need to have URIs but it would be helpful to have a URI for the core profile, too, so that a server can tell the client that the ODRL data conforms to the core profile.

> When would ODRL data not conform to the "core profile" ?

are we talking about core profile as in https://w3c.github.io/poe/vocab/#vocab-core
or as in https://w3c.github.io/poe/vocab/#vocab-common?

If it's https://w3c.github.io/poe/vocab/#vocab-core, than (as @riannella pointed out) there's no reason to have such a URI, because **ALL** ODRL data has to conform to the core.

**Comment by larsgsvensson** [comment]
>  ALL ODRL data has to conform to the core.

Yes, but the point is that when you de-reference a URI in order to get a document (e. g. an ODRL document) all the server currently tells you is the media type of that document, e. g. `text/turtle` or `application/ld+json`. It does not tell you that it is an ODRL document. Sending  a profile URI with the document can help the client to understand that what he gets is an ODRL document conforming to the core profile so that it knows what information it can expect inside the document and how that is organised, e. g. which SPARQL queries it can perform or which XPaths would work.

**Comment by simonstey** [comment]
> It does not tell you that it is an ODRL document. Sending a profile URI with the document can help the client to understand that what he gets is an ODRL document conforming to the core profile

aah I see. @riannella's and my point was that you don't need a URI for stating that an ODRL document **conforms** to ODRL core (it has no other choice than doing so). However using a URI to tell a client that the stuff it gets **is** ODRL data, is a different story.. How do other Vocabs handle that? 

Couldn't we adopt something similar as outlined in https://www.w3.org/TR/prov-aq/ ?

**Comment by nitmws** [comment]
Note on @larsgsvensson : the ODRL Community applied for a Media Type registration at IANA and this was rejected as that version of ODRL was not owned by a "reliable standards body". A W3C-owned ODRL should be accepted. 

Such a media type should apply to all profiles of ODRL. A Media Type registration could include having a parameter "profile" - a well known example for that is "text/plain;charset=utf-8". Open issue: what to apply as profile value - a full URI?

An ODRL Media Type would cover all types of communication using a MIME/Media Type. What other types of communication need a different identifier?

**Comment by iherman** [comment]
@nitmws, @larsgsvensson : I am not fully convinced about the media type. Would it be an extension to JSON, something like `application/odrl+json`? Or an extension to Turtle? The problem I see that processors that do recognize `json-ld` would not recognize `odrl+json`, and, afaik, `odrl+ld+json` is not a valid media type registration...

**Comment by philarcher** [comment]
I would also argue against a media type. Since ODRL can be serialised in multiple ways, and have multiple profiles, it seems to me that Occam's razor is to mint  URI for the core profile which tells you that the JSON-LD, or Turtle, or XML, or Foo, conforms (only) to the core profile. Any other profile can assume that the processor understands core, of course. But, again, I really think this WG would do well to defer as much of the discussion as possible to the DXWG or we may end up with Recs later this year that are at odds with early drafts of highly relevant work that may render it obsolete. We can say now that profiles need a URI. Those profiles may be available in multiple serialisations for human and machine readability and will therefore have their own mime types. I am not arguing for creating a dependency on the DXWG, rather, I think we can just talk in terms of profiles without going into detail about how they should be serialised. My inclination is to define a URI for the default/core profile as a means of indicating that a client or Policy *only* uses the core - however unlikely that is. This would then support the kind of negotiation by profile that Lars is working on.

**Comment by nitmws** [comment]
@philarcher1  the end date of the [DXWG](https://www.w3.org/2017/dxwg/charter) is 30 June 2019, in almost exactly 2 years. What can we expect by September 2017?

**Comment by larsgsvensson** [comment]
@nitmws  What do you need by September 2017? If you decide on an own media type, you loose the possiblilty to mix and match information, e. g. to put ODRL data in the same graph as other information.
The DXWG can promise that we'll eventually deliver a mechanism to negotiate on profiles. A (negotiation) profile is -- as @philarcher1 said -- independent of the media type and specifies "additional structure and/or semantics, on top of one or multiple media types." (Quote taken from [public-dxwg-wg](https://lists.w3.org/Archives/Public/public-dxwg-wg/2017Jun/0089.html)).  For a further explanation of what we envision, see [this post](https://lists.w3.org/Archives/Public/public-dxwg-wg/2017Jun/0090.html) by @rubenverborgh

**Comment by philarcher** [comment]
+1 to Lars. I am not suggesting that we create a dependency on DXWG, that would be a bad move. Rather, I'm suggesting that POE can afford not to be prescriptive in how profiles are serialised and just define what information needs to be included in a profile - however it's done. The detail of how to share a profile of any vocabulary is a specific deliverable of DXWG and we, in POE, can just point to that as a source of future information. Members of the POE WG might want to contribute/comment on the DXWG work where ODRL profiles would be an important use case.

**Comment by riannella** [comment]
Is this a reasonable proposal:

In the Profile section: https://w3c.github.io/poe/model/#profile
we state that the "default" value for the profile property is "http://www.w3.org/ns/odrl/2/"
(if you don't use any other community Profile) and that URI may be used in comms between systems in identifying the ODRL core profile being exchanged.

**Comment by larsgsvensson** [comment]
No, I don't think that it would be correct to use the ODRL Namespace URI to denote the profile. The Namespace URI points to an owl:Ontology/voaf:Vocabulary and that is not the same thing as a profile. My suggestion would rather be something like "http://www.w3.org/profiles/odrl/2/" but of course we cannot just hijack the W3C webserver to implement that. Perhaps @philarcher1 has a suggestion.

**Comment by iherman** [comment]
I agree with @larsgsvensson : using the URI of the ontology proper is a bit muddy. But it can be as simple as "http://www.w3.org/ns/odrl/2/coreProfile", or something similar. Introducing a separate 'path' for profiles on the W3C space may suggest that we will use that path to "register" different profiles in future, which I do not think we should commit ourselves to.

**Comment by vroddon** [comment]
I understand this solution does not preclude using third party URI's, like `http://my_industry.org/odrl/myProfile`...

**Comment by larsgsvensson** [comment]
> I understand this solution does not preclude using third party URI's, like http://my_industry.org/odrl/myProfile...

That is in my opinion correct, particularly since every community profile MUST have its own URI. But as long as you use the core profile, you SHOULD use the Core Profile URI.

**Comment by riannella** [comment]
Ok, how about: `http://www.w3.org/ns/odrl/2/core`

Will there (potentially) be any requirement to return something if this is dereferenced?

**Comment by iherman** [comment]
@riannella that URL works for me.

As for the return value: no different than dereferencing any other term in the ontology...

**Comment by larsgsvensson** [comment]
@iherman 
> As for the return value: no different than dereferencing any other term in the ontology...

And that is?

@riannella 
> Will there (potentially) be any requirement to return something if this is dereferenced?

What we will propose in the DXWG is that the profile URI SHOULD return some kind of description, but the provider is not compelled to do so. Also there SHOULD be links from the profile document to schemas implementing that profile (e. g. a SHACL document or an XML schema). Exactly what that will look like is still work-in-progress...

**Comment by iherman** [comment]
@larsgsvensson 

>> As for the return value: no different than dereferencing any other term in the ontology...
>
> And that is?

Good question, I actually do not know how the ontology would be presented in general. Ideally, there should be a content negotiation: expecting HTML would lead to a (reference of) human readable text, otherwise an RDF statement defining that term to be an individual, a property, a class, etc. 

But we may not have the time/energy to do that, so the dereferencing may just redirect to a fragment in the ontology itself.

**Comment by riannella** [comment]
Added core profile: 0c26559afa6a917fa0cbf72ba756756b4d0f67cf

Not sure what odrl:core is, so made it an owl:Thing

**Comment by larsgsvensson** [comment]
owl:Thing is always an option, but I saw skos:Concept, too... Until when can we propose changes to the two documents referenced in the commit? The DXWG will be working on a definition and it would be good to know if we _might_ be able to have that finished on time for this WG.

**Comment by riannella** [comment]
We are working now to reach CR - _hopefully_ in August.

But if the core URI is non-normative (won't be tested), small changes can be made after that.

**Comment by larsgsvensson** [comment]
OK, we definitely won't have a solution in August, so it's probably best to leave it as it is
