### ISSUE TITLE
XML Schema issues

### ISSUE THREAD

**Issue by nitmws** [w3c/poe#276]
I had a look at the ODRL XML Schema at http://w3c.github.io/poe/vocab/ODRL22.xsd - referrenced from the CR Vocabl document, in the non-normative section [5.3 XML ](https://www.w3.org/TR/2017/CR-odrl-vocab-20170926/#xml) and found details which do not align the the IM of the CR:

* Policy/@profile and @inheritFrom take only a single URI. A simpleType defined as list of xs:anyURI could be used to solve that issue.
* Asset/@partOf: same as above.
* Constraint type: the @rightOperand takes the simpleType listOfValues - fine. But the @rightOperandReference takes only a single URI. Solution same as above.
* what about Logical Constraints? This class is not implemented by the XML Schema.
* using the o:Duty type for consequences and remedies is questionable: the IM defines these properties should not have a consequence property, using this type allows to have consequences (and this way and endless nesting of consequences :-( ). A new type like DutyNoConseq should be defined without a consequence child element.

**Comment by riannella** [comment]
First 3 points fixed.

Logical constraints are implemented as #IDs on the rightOperand (with an name only)
(this is minimal change for XML implementors)

RE: Duty consequence: I can understand this, there are heaps of rules in described in the IM that are not captured in the XML Schema (due to its inflexibility to describe them) - even the ontology does support this particular constraint. I have added a note to the schema.
