### ISSUE TITLE
Support JSON-LD

### ISSUE THREAD

**Issue by riannella** [w3c/poe#46]
We will support JSON-LD serialisation (not current JSON as in V2.1) as close as possible to ODRL Ontology.
Update spec. required.

**Comment by riannella** [comment]
See email thread starting here: https://lists.w3.org/Archives/Public/public-poe-wg/2016Oct/0020.html

**Comment by riannella** [comment]
Now that we will support JSON-LD, does that mean we don't have to define our own JSON Schema as it is auto-generated from the ODRL Ontology?

**Comment by iherman** [comment]
> Now that we will support JSON-LD, does that mean we don't have to define our own JSON Schema as it is auto-generated from the ODRL Ontology?
> 
I indeed do not think we should define a JSON Schema. I believe, apart from what we already do in the information model document[1], we have to define a JSON-LD @context file that maps the JSON-LD to the RDF vocabulary and we *may* define, informally, JSON-LD Frames that define a preferred way of expressing things in JSON-LD (and that should reflect the way all the examples are in the info. model document. 

At least this is the way the Anno WG did it, see[2].

Ivan

1. http://w3c.github.io/poe/model/ <http://w3c.github.io/poe/model/>
2. https://www.w3.org/TR/annotation-vocab/#json-ld-frames

**Comment by stuartmyles** [comment]
But wouldn't this same logic apply to the XML encoding too? Why not just
auto-generate XML from the ODRL Ontology?

On the other hand, don't we need an JSON schema for people who don't care
about (or don't like or have never heard of) RDF?

Regards,

Stuart

**Comment by iherman** [comment]
@stuartmyles, there are some major differences between RDF/XML and JSON-LD.

I believe it is possible to come up with an encoding of the model that **is** acceptable for JSON users who are not RDF users. JSON-LD has been defined with that goal in mind. It is not perfect, but I believe it goes a long way in this direction. Several WG-s have done this (Social Web, Annotation, even the CSV on the Web). 

RDF/XML is and remains problematic even for XML users. There is no equivalent to the JSON-LD frames that would allow to use some sort of an RDF/XML dialect and. primarily, there is no equivalent to the JSON-LD `@context` notion that can hide most of the features that irritate non-RDF users (usage of various namespaces, for example).

**Comment by riannella** [comment]
I think @stuartmyles was talking about auto-generating the XML Schema from the Ontology?
This never works in practice, as you end up with a convoluted and crazy XML Schema design.
Hand crafting is the only way....yeah for me !

As for the auto-generation of the RDF/XML ontology from the turtle ontology, I am waiting on @nevali to update the script 👍

**Comment by iherman** [comment]
> I think @stuartmyles <https://github.com/stuartmyles> was talking about auto-generating the XML Schema from the Ontology?
> This never works in practice, as you end up with a convoluted and crazy XML Schema design.
> Hand crafting is the only way....yeah for me !
> 
Oops, my apologies. And XML Schema being very different from an OWL Ontology I tend to agree that relying on some automatism may be an issue.

> As for the auto-generation of the RDF/XML ontology from the turtle ontology, I am waiting on @nevali <https://github.com/nevali> to update the script 👍
> 


The question which is still open to me is whether we would keep the XML serialization on the agenda at all...

**Comment by riannella** [comment]
We still have XML implementations. When we asked the community in October, both Associated Press and Reuters News said they will use the XML encoding.

**Comment by iherman** [comment]
> On 13 Dec 2016, at 14:03, Renato Iannella <notifications@github.com> wrote:
> 
> We still have XML implementations. When we asked the community in October, both Associated Press and Reuters News said they will use the XML encoding.
> 

O.k. (But that is another discussion then; it should certainly not be RDF/XML.)

**Comment by stuartmyles** [comment]
Yes - I admit, I raised the question of auto-generating XML from the
Ontology, to illustrate why I think auto-generating the JSON from the
Ontology is also not a good idea.

I don't seriously think that we should auto-generate either XML or JSON. In
both cases, the auto-generating the schema will result in ugly documents,
Fine for people who never plan to work with the formats directly (i.e.
those who only like the RDF data model but are indifferent to how it is
expressed). But for people who only care about their preferred format (XML
or JSON) then they are going to be put off by the details of the
auto-generated encoding. And, worst case, create their own. This, for
example, is what happened with the PRISM Rights Expression Language: they
liked the ODRL data model, but decided to create their own XML encoding,
because they don't like some of the details of the ODRL 2.1 encoding. See,
for example,
http://www.prismstandard.org/specifications/3.1/Draft_Rights_Summary_Guide_3.1.htm#_Toc406232056

As Renato says, there are already implementations of ODRL in both XML and
JSON. Now, we can't make an omelette without breaking a few eggs. And, I'm
not under the illusion that what we will end up with is exactly the same
thing as ODRL 2.1. But I think this group should decide on purpose whether
they want to specify the XML and JSON encodings of the ODRL (POE) data
model. Or whether we are content for others to take the data model and make
up their own encodings, which is what I predict will happen, if POE doesn't
specify a JSON encoding.

Regards,

Stuart

**Comment by Jimflip** [comment]
Hi

I think this has been said before, but to just to clarify and support the opinion.
The JSON representation should be the JSON-LD simply with the @context removed.
We define and provide the @context which will give us a representation in JSON that we agree on.

If people define their own JSON representation that is their choice, but with the semantics removed and a different representation then its basically not interoperable.
They could provide something like an R2RML mapping back to JSON-LD or RDF from their JSON format, but basically thats not really relevant to us.

I suspect there is concern that a JSON-LD object with the @context removed is problematic? 
If so lets break down what exactly the perceived issues are.

Thanks,
James.

**Comment by stuartmyles** [comment]
> The JSON representation should be the JSON-LD simply with the @context
removed.

Yes, I agree with this,

But the suggestion is now that we don't need to even have a specific JSON
representation. Instead that we simply generate JSON (or JSON-LD) from the
ODRL Ontology. My view is that, if we go down this path - not specifying
"here's the JSON syntax" - then other people will craft their own.

Regards,

Stuart

**Comment by iherman** [comment]
To add what @Jimflip said: please look at

- the [Web Annotation Model](http://w3c.github.io/web-annotation/model/wd2/) document, that defines the annotation structures in JSON that happens to be JSON-LD (it does include a single `@context`)
- the JSON-LD [`@context`](http://w3c.github.io/web-annotation/vocab/wd/#json-ld-context) is defined in the separate (RDF) [vocabulary document](http://w3c.github.io/web-annotation/vocab/wd/), mapping the Annotation structures to RDF (if needed)
- we also have a JSON-LD [frame](http://w3c.github.io/web-annotation/vocab/wd/#json-ld-frames) that allows any valid JSON-LD encoding of the RDF vocabulary be represented the way it is defined in the Annotation Model document.

Note that the vocabulary (ie, the ontology) itself has been hand-crafted in Turtle. One of the exit criteria of that document is to prove that the `@context` we define maps the JSON version onto an RDF graph that is indeed valid per the ontology.

We have a number of implementers who use the JSON encoding as defined in the Annotation Model document, and they do not care about RDF. For them, that document defines a JSON encoding. Others care about the RDF aspect, and they use it accordingly.

I believe that approach (also used by the Social Web WG) can be reproduced by the POE work (and may already been done in our model document, in fact).

As for the remark of @stuartmyles : the JSON encoding _is_ necessary, I believe, ie, it should not be generated by the ontology because there are different ways to represent a graph in JSON-LD. As he says, we would loose interoperability if we did differently.

**Comment by riannella** [comment]
Hi @stuartmyles - any ideas how we update the current JSON section  to JSON-LD ?

**Comment by riannella** [comment]
Dear all @stuartmyles @iherman @nevali @Jimflip @vroddon 

@nitmws has said that we can create JSON-LD from the http://w3c.github.io/poe/vocab/ODRL22.ttl at http://rdf-translator.appspot.com/ 

It certainly produces some nice JSON-LD output.

The JSON-LD Context defined for the Annotation Vocab looks like this:
   http://w3c.github.io/web-annotation/vocab/wd/#json-ld-context

@iherman Do you know how they created this context? By hand??

**Comment by iherman** [comment]
@riannella : to be honest, I do not know. CC-ing this to @azaroth42 (https://github.com/azaroth42, a.k.a. Rob Sanderson).

(will also send a direct mail)

**Comment by azaroth42** [comment]
Yes, we created it by hand. The rationale being that the context is not just a simple translation of the schema, but instead an abstraction layer to turn an ontology into an API that's understandable and (more importantly) idiomatic for developers as opposed to ontologists.  For example, `oa:hasBody` in the ontology (following the best practice of verb phase for predicate) is just `body` in the JSON-LD (following JSON conventions).

I'll try and take a look at the JSON work here (now that the Annotation specs are in PR).

[and hi @stuartmyles! :)]

**Comment by azaroth42** [comment]
Example context and the first example from ODRL2:  http://tinyurl.com/jyude82

**Comment by riannella** [comment]
So, what then would be the manual process to create the (simplest) JSON-LD Context?

Do we just take all (200 or so)  ODRL ontology terms (URIs) and list them like:

    "Policy":           "o:Policy",
    ....
    "policyUsage": "o:PolicyUsage"

And if the term is a property (and has a URI object) then we say:

    "target":     {"@type": "@id", "@id": "o:target"},

Would that work?

**Comment by stuartmyles** [comment]
I've just noticed these emails with @stuartmyles mentions in them. Are
these meant to be me alerting me somehow?!!?

Anyway, now that I've seen it I will trace back through the thread and see
if I can contribute in any way. Apologies for not checking this email
account sufficiently diligently before now.

Regards,

Stuart

**Comment by azaroth42** [comment]
@riannella That should work :)  You would want to distinguish between @type:@id, and @type: @vocab if you want to avoid prefixes in the values.  The distinction is described here:  https://www.w3.org/TR/json-ld/#type-coercion

**Comment by stuartmyles** [comment]
I'm a bit confused as to where this (creating a JSON-LD mapping) stands now.

Based on Rob and Renato's emails, it sounds like someone needs to create a
JSON-LD context file. And that, essentially, it needs to be done manually.
Is that right? If so, is there someone already working on doing that? If
not, then I can volunteer. (I just don't want to do it if someone - likely
better qualified than me - is already slaving away).

I also looked at Rob's example earlier in this thread and it looks good to
me. (In other words, it seems like it would be fine to ignore the JSON-LD
context and just handle it like a proper JSON file, which is my definition
of "good" in this situation!)

http://json-ld.org/playground/?startTab=tab-compacted&copyContext=true&json-ld=%7B%22%40context%22%3A%7B%22odrl%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fodrl%2F2%2F%22%2C%22Set%22%3A%22odrl%3ASet%22%2C%22Permission%22%3A%22odrl%3APermission%22%2C%22Prohibition%22%3A%22odrl%3AProhibition%22%2C%22target%22%3A%22odrl%3Atarget%22%2C%22action%22%3A%7B%22%40id%22%3A%22odrl%3Aaction%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22permission%22%3A%22odrl%3Apermission%22%2C%22prohibition%22%3A%22odrl%3Aprohibition%22%2C%22reproduce%22%3A%22odrl%3Areproduce%22%2C%22modify%22%3A%22odrl%3Amodify%22%2C%22id%22%3A%22%40id%22%2C%22type%22%3A%22%40type%22%7D%2C%22id%22%3A%22http%3A%2F%2Fexample.com%2Fpolicy%3A0099%22%2C%22type%22%3A%22Set%22%2C%22permission%22%3A%7B%22type%22%3A%22Permission%22%2C%22target%22%3A%22http%3A%2F%2Fexample.com%2Fasset%3A9898%22%2C%22action%22%3A%22reproduce%22%7D%2C%22prohibition%22%3A%7B%22type%22%3A%22Prohibition%22%2C%22target%22%3A%22http%3A%2F%2Fexample.com%2Fasset%3A9898%22%2C%22action%22%3A%22modify%22%7D%7D

**Comment by riannella** [comment]
@stuartmyles no one has started the manual creation of the JSON-LD context file. Please do 👍 .
We need this asap to move the Vocab spec forward.

We also need to then update the narrative section on JSON-LD...I assume it will be shorter now?

**Comment by stuartmyles** [comment]
@azaroth42 looking at your example, it seems you rewrote the JSON - was that to make it easier to map it into JSON-LD? If so, I have some questions...

Here is the original JSON example:

{
    "policytype": "http://www.w3.org/ns/odrl/2/Set",
    "policyid": "http://example.com/policy:0099",
    "permissions": [{
        "target": "http://example.com/asset:9898",
        "action": "http://www.w3.org/ns/odrl/2/reproduce"
    }],
    "prohibitions": [{
        "target": "http://example.com/asset:9898",
        "action": "http://www.w3.org/ns/odrl/2/modify"
    }]
}

And here is your rewritten version (minus the context):

{
  "id": "http://example.com/policy:0099",
  "type": "Set",
  "permission": {
    "type": "Permission",
    "action": "reproduce",
    "target": "http://example.com/asset:9898"
  },
  "prohibition": {
    "type": "Prohibition",
    "action": "modify",
    "target": "http://example.com/asset:9898"
  }
}

One obvious problem with the JSON-LD version: you can't have more than one permission or prohibition in a given expression! Is that a necessary restriction for the JSON-LD?

Also, I use full URLs for the actions (e.g. "action": "http://www.w3.org/ns/odrl/2/modify") whereas your example uses URLs that are built into the context (i.e.     "action": "modify"). The use of full URLs is so that ODRL users can plug in whatever vocabulary of actions they want. Are we no longer able to use full URLs in JSON-LD?

**Comment by azaroth42** [comment]
You can specify that the property must be expressed as a singleton list, rather than reducing it to just an object. I simplified down, but that's not necessary for JSON-LD, just a choice I made at the time :) 

And yes you can use full URLs. I think its a good practice for static URLs (such as using URLs as identifiers like 'modify') to reduce it to an entity in the context ... but that's certainly not necessary.  The JSON in your example could, with a slightly modified context, be JSON-LD without change.

Similarly, `id` and `type` are good practice but also not necessary ... they could be policytype and policyid.

**Comment by riannella** [comment]
Just saw this job posting:
  https://www.upwork.com/job/Create-JSON-Context-Definition-for-ODRL_~0156ff5fdb318c478f/

Anyone have any idea who it could be from?

**Comment by riannella** [comment]
Should we map ODRL's policy uid and type to @id and @type in JSON-LD?

**Comment by simonstey** [comment]
> Anyone have any idea who it could be from?  

stuart as it seems :D  (you can toggle open the feedback on the very bottom)

> mapping of uid/type

yes

**Comment by riannella** [comment]
ok, cool, could be the first time anyone has made direct money from ODRL ;-)

@stuartmyles please ensure you use the latest turtle at: http://w3c.github.io/poe/vocab/ODRL22.ttl
(not the ODRL21 version)

**Comment by stuartmyles** [comment]
Yes, this was from me. (It is good that you've seen it - I actually haven't
gotten any responses, yet, so I wasn't certain whether it had worked! I've
used this service a couple of times in the past and I normally get several
responses over night. However, none so far, which is a bit ominous).

I looked at creating the ODRL Context myself. After some study, I decided
that I could get to the level of being able to distinguish a good @context
from a poor one, most likely. However, I don't think I can quickly become a
sufficient expert in JSON-LD to be able to design a good context. I'm
pretty confident in working with XML or JSON schema design, since I've
worked in both areas for several years. But all I've really done for
JSON-LD is read the primer and a few other associated documents.

I understand that we want to have the JSON-LD @context as part of the POE
work, although I personally don't see that there's any business value in
it. And, from what I can tell, it is unlikely that I myself will ever use
JSON-LD in this or other contexts, so it doesn't seem really worthwhile me
trying to become an expert in it. So, I thought I would try to find someone
who might be able to provide that expertise. I've turned to upwork to try
to find such a person.

As I said, I haven't received any bids, so it could be that this isn't
going to work out. I also searched to see if I could find anyone with
JSON-LD expertise. Plenty of people with JSON skills and even RDF. But no
one even mentions JSON-LD (which reinforces my belief that there is no
direct business value). However, if this is the way for us to pay off the
"JSON-LD tax" and keep the overall POE effort moving forward, it would be
worth it to me.

Regards,

Stuart

**Comment by riannella** [comment]
I am slightly confused too...(being weened on XML...:-)

Doesn't the JSON-LD context *also* act as the JSON schema?

So in the Annotation json-ld context: http://w3c.github.io/web-annotation/vocab/wd/#json-ld-context

Then when a JSON person writes  "Annotation", it really means "oa:Annotation" (and the latter keeps LD people happy)? ?

**Comment by iherman** [comment]
> Doesn't the JSON-LD context also act as the JSON schema?

These two are completely different. [JSON Schema](http://json-schema.org/) is a separate semi-specification; "semi" in the sense that I am not sure it is really stable. Nor do I know how widespread it is. A JSON-LD context is very different. It does not "check" the JSON file (as a JSON Schema would do) but it rather maps the JSON content on something that RDF processors like.

> So in the Annotation json-ld context: http://w3c.github.io/web-annotation/vocab/wd/#json-ld-context
>
>Then when a JSON person writes "Annotation", it really means "oa:Annotation" (and the latter keeps LD people happy)? ?

Yes. A JSON-LD parser, when generating RDF, will expand "Annotation" into the URL.

**Comment by riannella** [comment]
So what do we do?

**Comment by iherman** [comment]
I am not sure I understand the question. Didn't we agree that we use JSON-LD as an encoding? If so, we must have a JSON-LD context file. What is the question?

**Comment by riannella** [comment]
Yes we did, but it seems that then does not address JSON developers (as well).
I had hoped/assumed that we were going to support both - thru the "context".

**Comment by iherman** [comment]
You mean because it is not a JSON Schema, too?

I do not know how widespread is the usage of JSON Schema in the JSON developers' community. The fact that (afaik) it is still a moving target is not a good sign.

As far as I remember (@azaroth42 ?) we did look at JSON Schemas in the Annotation WG, and wondered whether it was worth defining a separate Schema file. But ended up not doing it.

In any case, it would indeed be a _separate_ work item to do so.

**Comment by azaroth42** [comment]
[JSON Schema](http://json-schema.org/documentation.html) is primarily a validation tool, in the same way that XML schemas are. We use it in the test suite for the Annotation WG to validate that documents conform to the specific JSON-LD serialization required, but did not make a single uber-schema as the complexity far outweighed any benefits.

JSON-LD's context document just maps from JSON to RDF, and does not make any requirements on structure or cardinality of properties or values.  The two are mostly orthogonal, other than that they both need to refer to the names of keys in the JSON.

As far as use within the JSON developer community ... I haven't seen significant adoption, but it could be part of back end data management workflows.

**Comment by riannella** [comment]
@stuartmyles 
I've attempted to create the JSON-LD context file for ODRL. See: 
   https://raw.githubusercontent.com/w3c/poe/gh-pages/vocab/ODRL22.jsonld

@azaroth42 
I am not sure if you can have a look at this? I followed the template used by the annotation spec.
I also tried to verify this in the JSON-LD playground but it gives me a processing error...and not sure where!

**Comment by stuartmyles** [comment]
Hi Renato,

How did you create the JSON-LD file? Was it automatically or by hand?

Right now, it won't work, since it doesn't match the JSON examples. Also, I
notice some odd typos, e.g.

"function":           {"@type": "@id", "@id": "odrl:fuction"},

Which is why I'm wondering how you did it.

However it is something and I can try to alter it to actually match the
JSON schema.

I have gotten one person offering to help with the job posting. But they
asked for three times what I was offering for the fee! And they said they
would do the thing I said I *did not* want: to merely automatically
generate the JSON-LD from the Ontology.

Regards,

Stuart

**Comment by riannella** [comment]
I wrote it by hand (2 hours of cut, copy, paste ;-)

I used the Annotation spec JSON-LD context as the template:
  http://w3c.github.io/web-annotation/vocab/wd/#json-ld-context

Basically, all classes, individuals, and properties (that are not taking URI objects) become:
   "xxx": "odrl:xxx"

Any property that takes a URI object becomes:
   "xxx":                 {"@type": "@id", "@id": "odrl:xxx"}

And where we are more specific, we can use the exact xsd:datatype in the first @id 

That's the pattern I followed...I *hope* its correct...but I may have missed something fundamental ;-)
(and, of course, I made some typos ;-)

I will email the JSON-LD editors direct (I know two of them) and ask them to verify/help us out...

(I think the freelancer option is not the best ;-)

**Comment by riannella** [comment]
Update: Gregg Kellogg (one of the JSON-LD editors) has agreed to help us out...

**Comment by gkellogg** [comment]
Well, one thing that makes the context invalid is on line 151, where `meteredTime` should be `odrl:meteredTime`; that seems to be the immediate source of the issue you found in the playground.

There are some other things you should consider:

As you discuss, properties who's range is a resource rather than a literal (similar to owl:objectProperty) should typically have `@type: @id`. However, then the resource comes from a constrained vocabulary, where the instances are defined in the context, you should use `@type: @vocab`.

This is due to the expansion rules, where `@type: @id` expands IRIs relative to the document base, and `@type: @vocab` relative to the vocabulary base, which also means they can be terms defined in the `@context`.

For example, the property `leftOperand` has a range of `LeftOperand`, which includes `meteredTime` as a member. So, I would make the term definition as follows:

```json
{"@context": {
  ...
  "leftOperand":          {"@type": "@vocab", "@id": "odrl:leftOperand"},
  ...
}
```

This way, if you have something like `{"leftOperand": "meteredValue"}` it will expand as you expect.

Another thing to consider is if you want to make your context also be a vocabulary document. For example, we did this for [CSVW][csvw], and [Web Ontology][oa] took a similar tack. This way, you can feed both the OWL/RDFS vocabulary and the context at the same time, but it does come at the cost of having a larger document.

I typically use a script to generate all the vocabularies. For example, the CSVW [script](https://github.com/w3c/csvw/blob/gh-pages/ns/mk_vocab.rb) takes a CSV input and generates Turtle, JSON-LD and HTML+RDFa.

[csvw]: https://www.w3.org/ns/csvw
[oa]: https://www.w3.org/ns/oa

**Comment by riannella** [comment]
thanks @gkellogg for your review and suggestions!

**Comment by riannella** [comment]
I have updated the JSON-LD context file to use @vocab where appropriate.
Also updated the JSON-LD section (very minimal).

**Comment by gkellogg** [comment]
Be careful with @vocab, if you think this will be combined with other contexts.

**Comment by riannella** [comment]
Thanks for the warning @gkellogg - can you give us an example of what could go wrong?

**Comment by gkellogg** [comment]
When combining contexts, the last one wins. I recommend the use of @vocab only when used by the final author of a JSON-LD document. If you explicitly define all terms in your vocabulary, you avoid this situation.

**Comment by stuartmyles** [comment]
Here's a draft JSON-LD context which appears to support all of the existing
JSON encodings:

https://dl.dropboxusercontent.com/u/8555005/context.json

I want to do more testing, though, just to make sure.

Note that one difference in this ODRL Context (versus the one that Renato
has been developing) is that it follows the convention we established for
JSON - that explicit URIs always be used. This dramatically simplifies the
@context, since it doesn't require the values of things like "leftoperand"
to be included within the @context. This fits with the concept of different
vocabularies (such as, say, RightsML) being able to be plugged into the
JSON. If you don't follow that approach, then you would need a different
@context file for a RightsML document versus an ODRL document, even if the
only difference was some additional vocabulary items.

There are some changes in the JSON spec that need to be addressed. Mainly,
these are bugs in the original spec.

Regards,

Stuart

**Comment by riannella** [comment]
What is the impact then, if any, of *not* enumerating all the actions?
(I ask since I see both the W3C Annotations and Activity Streams JSON-LD contexts do...)

**Comment by riannella** [comment]
There are some technical issues with the new context - namely "scope" is a property of a Party (or Asset) and we have an explicit "assignee_scope" - meaning every role would need to define that?

**Comment by stuartmyles** [comment]
Good catch! I think the problem here is that we didn't cover the pattern
properties in the ODRL Context.

Here it is in the JSON Schema:

"patternProperties": {
                "^[a-z]+party": {
                    "type": "string",
                    "format": "uri"
                },
                "^[a-z]+_scope": {
                    "type": "string",
                    "format": "uri"                }
            }

What this is saying is that other parties and scopes are possible, beyond
assigner and assignee. Let me see if we can find a JSON-LD equivalent.

Regards,

Stuart

**Comment by riannella** [comment]
Why can't you just have a "scope" property?
That is what we show in the Info Model examples...
See here: http://w3c.github.io/poe/model/#party-scope

**Comment by riannella** [comment]
Some other points...
1 - pollicyid -> uid
2 - policytype -> type
3  - policyprofile -> profile
4 - permissions -> permission
5 - constraints -> constraint
6 - rightoperanddatatype -> datatype
7 - rightoperandunit -> unit
8 - duties -> duty
9 - prohibitions -> prohibition
10 - rightOperandReference missing
11 - what about the operators?

**Comment by riannella** [comment]
What about all the Classes?

Should we support:

        "assignee": [{
                "@type": [ "odrl:Party", "vcard:Organisation"],
                "@id": "http://example.com/org44/",
                ...
        }]

**Comment by stuartmyles** [comment]
Apologies for the delay in getting back to you on this. I was out of the
office yesterday.

A couple of things...

The JSON-LD @context that I provided *does* support scopes being mapped
into the RDF equivalent, so it doesn't look we need a change there.

However, in the process of looking more closely at how the "scope" property
is defined in the ODRL 2.2 ontology, I think there may be a bug there? Here
is the TTL:

:scope
a rdf:Property , owl:ObjectProperty ;
rdfs:isDefinedBy odrl: ;
rdfs:label "Scope"@en ;
skos:definition "The identifier of a scope that provides context to the
extent of the entity."@en ;
skos:note "Used to define scopes for Assets and Parties."@en ;
rdfs:range [
a owl:Class ;
owl:unionOf ( :Asset :Party ) ;
] .

As I understand it, that means that the value of :scope must be either
Asset or Party. But surely it should be :PartyScope?

(I will also respond to your request to alter all of the property names and
of "complexifying" the JSON structure - but that is a different thread).

Regards,

Stuart

**Comment by stuartmyles** [comment]
So, I would say there are two overall requests here to alter the JSON
representation of ODRL:

1. Rename all of the properties - generally, take off the prefixes to bring
the JSON property names into alignment with the names in XML or RDF. For
exampe, no longer "policytype" but "type".
2. Rather than simple, flat structures (such as { "assignee" : "
http://example.com/org44/" } ) instead have lists of complex, anonymous
obects, with multiple properties.

So, I want to briefly explain *why* we decided to take the design approach
to JSON that we did for ODRL 2.1 - it wasn't just an accident! I go into
more detail in
https://stuartmyles.blogspot.com/2014/08/json-design-principles-and-lessons.html
but, briefly:

1. It is possible to mechanically translate from XML (or RDF) into JSON.
However, like most mechanical translations, this is not going to result in
"natural" JSON. In my experience, adoption of a standard is often driven by
initial impressions - if I don't like the look of your markup (particularly
in the JSON world) I may well decide to design something simpler and
easier. (Although this can happen with XML too. Remember that PRISM
"adopted ODRL" but decided they wanted a different syntax for it
http://www.prismstandard.org/specifications/3.1/Draft_Rights_Summary_Guide_3.1.htm#_Toc406232056
because they disliked the XML Serialization).

2. A big reason that developers like JSON is that it is much easier to deal
with than XML or RDF. (These days, I even find myself converting from XML
to JSON for a lot of tasks). However, a lot of that simplicity evaporates
if the JSON has complex structure - particularly anonymous objects. That's
because there still aren't a lot of great options for querying complex
JSON. (Although I hold out a lot of hope for the upcoming XQuery 3.1
https://www.w3.org/TR/2017/PR-xquery-31-20170117/). For most JSON
developers, flat lists of properties, with very little hierarchy, is the
way to go. (And, of course, you can't repeat property names, which is why I
prefixed the ODRL names, hence "policytype" rather than "type"). We didn't
quite as bit of experimentation with different JSON libraries and tools in
order to formulate these "best practices".

3. Some things are simply stylistic choices, to aid readability. Which is
why "permissions" for the list of permissions, rather than "permission" -
which doesn't really make sense as the name of a list.

Now, like any design issue, a lot of these decisions are based on various
trade-offs. And other people have come up with slightly different choices
in their style guides. For example, I favour lower_snake_case (since it
doesn't cause problems with generated class names). But others prefer
CamelCase, since it saves more bytes. And it could be that we decide that
we do want to revise (or update) the way we design our JSON. We might break
backwards compatibility, but that can be worth it for a better design.
However, I would ask that, if we do decide to change things, then we do so
with the goal of making the JSON experience with ODRL as good as possible,
rather than just seeing the JSON encoding as being a poor relation to the
RDF.

Regards,

Stuart

**Comment by riannella** [comment]
Fixed the scope property in the ontology, and added AssetScope class.

**Comment by riannella** [comment]
It's not clear why PRISM choose to create their own XML Schema. Ironically, the schema they have published has serious errors.

**Comment by riannella** [comment]
In 1) the issue is not that we are translating from XML to JSON, but from the Information Model to JSON. So we want to preserve the IM terms and concepts as much as possible and only change them when there is a technical need or benefit (eg uid->@id)

If you look at the JSON-LD examples in the IM, are they ok?

**Comment by riannella** [comment]
Just noticed some of the examples in the IM repeat property names  - will fix....

**Comment by riannella** [comment]
For 2), are you asking for no complex structure in the JSON-LD?

For example, See Example 18 in: http://w3c.github.io/poe/model/#role

**Comment by riannella** [comment]
For 3), best practice (from a metadata perspective, ISO11179 etc) is to not use plurals.

Otherwise, all terms would need to be plural, as we support multiple targets, actions, assignees, assigners...

**Comment by riannella** [comment]
JSON-LD context now published at: http://www.w3.org/ns/odrl.jsonld
All examples in IM will now use this, and remove the "odrl:" prefix from values/objects

Context will now use "uid" and "type" (not @id and @type in examples)
(and has been updated)

**Comment by iherman** [comment]
@riannella at this moment the context file uses 'id' and not 'uid'. Should I change this?

**Comment by riannella** [comment]
Yes, I just did: https://github.com/w3c/poe/blob/gh-pages/vocab/ODRL22.jsonld
(but can't write to w3c.org/ns/)

**Comment by iherman** [comment]
I did the update. (Indeed, that folder is team-writable only.)

You can just ping me or Phil if an update is necessary.

**Comment by riannella** [comment]
I have updated all the examples in the IM to use the new JSON-LD @context URI and now uses "type" and "uid" properties

**Comment by iherman** [comment]
Overall, it looks good. However... unfortunately, Example 25 is incorrect. Incorrect JSON at the moment and, unfortunately, it is not even that easy to do it in a proper JSON-LD. Indeed, JSON-LD becomes a bit complex (too complex for my taste) when the idea is to have a forest, so to say, and not a tree of objects. (A separate keywords, `@graph` must be used, AFAIK; @gkellogg should advise us.)

I see two possibilities.

1. Fold in `http://example.com/policy:7171` into the tree as the value of `target` in the duty; or
2. Cut the example into two to make it clear that these are two resources completely separated from one another (and it is up to a ODRL processor to combine the graphs before handling them)

I have only a mild preference for the second option, but only mild.

**Comment by gkellogg** [comment]
Yes, there are a couple of ways to go when you have more than one node object at the top-level:

1) Wrap them in an array `[{"@context": .., ...}, {"@context": .., ..}`
2) Wrap them all in `@graph` with a shared context `{"@context": ..., "@graph": []}`.
3) Find a common object property and use a reverse relationship. For example, in an RDFS document, this might be `rdfs:isDefinedBy`, in which case you can do something like we do for [CSVW](https://github.com/w3c/csvw/blob/gh-pages/ns/csvw.jsonld):

```json
{
  "@context": {
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
      "rdfs_classes": {
        "@reverse": "rdfs:isDefinedBy",
        "@type": "@id"
      },
      ...
  },
  ...,
  "rdfs:classes": [
      {
        "@id": "csvw:Cell",
        "@type": "rdfs:Class",
        "rdfs:label": {
          "en": "Cell"
        },
        "rdfs:comment": {
          "en": "A Cell represents a cell at the intersection of a Row and a Column within a Table."
        }
      },
      {
        "@id": "csvw:Column",
        "@type": "rdfs:Class",
        "rdfs:label": {
          "en": "Column Description"
        },
        "rdfs:comment": {
          "en": "A Column represents a vertical arrangement of Cells within a Table."
        }
      },
      ...
  ]
}
```

You can, of course, make it multiple JSON-LD documents, and use the graph merge, but adding `[]` around them solves this problem at the expense of repeating `@context`.

JSON-LD _is_ JSON, so we need to play be the rules. That said, we are in the process of doing a community update for [JSON-LD 1.1](http://json-ld.org/spec/latest/json-ld/) and reasonable ideas are being entertained, when they are not too disruptive. One feature we're adding is [ID Maps](http://json-ld.org/spec/latest/json-ld/#node-identifier-indexing), which uses the `@container` property of a term definition to allow for indexing values. We could add `"@container": "@id"` as a top-level context element to set the default container value, in which case a top-level object might contain both an `@context` and identifiers to index node definitions. This would substantially change the way that JSON-LD looks, so I'm sure it would be controversial, but would be a fairly simple change to the algorithms. Hypothetically, your example might look like the following:

```json
{
    "@context": ["http://www.w3.org/ns/odrl.jsonld",
      {"@container": "@id"}
    ],
    "http://example.com/policy:6161": {
        "type": "Offer",
        "permission": [{
            "target": "http://example.com/wallpaper:1234",
            "assigner": "http://example.com/myPix:6161",
            "action": "distribute",
            "constraint": [{
                "leftOperand": "spatial",
                "operator": "eq",
                "rightOperand": "https://www.iso.org/obp/ui/#iso:code:3166:IT"
            }],
            "duty": [
                {
                    "action": "compensate",
                    "constraint": [{
                        "leftOperand": "payAmount",
                        "operator": "eq",
                        "rightOperand": "100.00",
                        "dataType": "http://www.w3.org/2001/XMLSchema#decimal",
                        "unit": 
                          "https://www.currency-iso.org/dam/downloads/lists/list_one.xml#EUR"
                    }]
                },
                {
                    "action": "nextPolicy",
                    "target": "http://example.com/policy:7171"
                }
            ]
        }]
    },
    "http://example.com/policy:7171": {
        "@context": "http://www.w3.org/ns/odrl.jsonld",
        "type": "Set",
        "permission": [{
            "target": "http://example.com/wallpaper:1234",
            "action": "display"
        }]
    }
}
```

**Comment by riannella** [comment]
Thanks for your suggestions @gkellogg.
Since this is the Information Model document (not the serialisations) and the JSON-LD are informative examples, then I would recommend we go for @iherman #2 option.

**Comment by riannella** [comment]
Now split Example 25 into two examples.

**Comment by riannella** [comment]
Any more comments on this issue??
