### ISSUE TITLE
isNeccessaryFor

### ISSUE THREAD

**Issue by riannella** [w3c/poe#98]
@simonstey @nitmws 
Updated isNeccessaryFor and added more processing rules.
Please  make any suggestions

**Comment by nitmws** [comment]
My  views on the current isNecessaryFor (IM of 31 January) in 3.8.1:
- I put this issue on the top - frankly it came up while writing all the bullets below: **is our thinking about this isNecessaryFor going in the right direction?** A logic combination of two constraints can be expressed by the operators or, xor or and. And if the left and the right operand must be satisfied then "and" should be used - and nothing else. But I think this isNecessaryFor is made to communicate: **this constraint must be processed at  the time the Action of a Rule should be executed because the result of a constraint (satisfied or not) referring to this Action may change over time** - and not: this constraint must deliver a result before another constraint is processed.. 
Practical view: checking if a time limit or a count limit is met should be checked when the action of the Rule should be executed and not let's say 2 or 5 or 15 minutes earlier.
(Was how to deal with the temporal change of left operand values ever discussed for ODRL? I can't recall it.)
Conclusion: we need this property for Constraint: **hasProcessAtActionTimeNeed** (ok, not short) - data type boolean, default value false. Definition: "If the value is true this constraint must be processed as close as possible to the time of executing the action it refers to as its result may change over time. This applies only to Left Operands of a constraint refering to an action."

My comments below are based on the previous discussions of this issue:

- re isNecessaryFor operator spec: 
-- My basic concern: isNecessaryFor doesn't fit into the context of Constraint Relations. They are made "for two constraints to be compared and processed accordingly" and the basic requirement for a Constraint as such is to deliver a boolean result: is the constraint satisfied or not. isNecessaryFor only defines that the leftOperand is a prerequisite of the right operand - but what's next??? Nothing like or, xor or and is defined -  even not as default value. Is it an implicit requirement to have 2 Constraint Relations with exactly the same left and right operands, one with isNecessaryFor and the other one with an or, xor or and operator?
-- What does "prerequisite"really mean - and what is the difference to the and operator? I interpret it as "the left operand must have delivered a result before the right operand is processed", this defines a temporal sequence for processing constraint results. If this is the intention then I suggest to rename the operator to "hasResultBefore". This also opens the logic relationships between the constraints (see my note above) to or, xor and "and". And we should comment/explain/define that the use of hasResultBefore only makes sense if the result of the left operand Constraint is expected to change over time, e.g. count, "live" times, etc. To require that the size of a digital image must deliver a result before the distribution channel constraint is checked doesn't make sense in practice.
-- conclusion: we must change the specification

- re "The isNecessaryFor operator ..." paragraph:
-- re "... unsatisfiable Constraint  ...": the spec of Constraint (first para in 3.8) defines if comparing left and right operand results is **true** then the Constraint is satisfied. Therefore: if its result is false it is unsatified. But what is meant by this use of "unsatisfied Constraint"? I interpret it means that for some reason the left and the right operand cannot be compared (e.g. because the result for the left operand cannot be retrieved). 
-- re " "recursive chaining" ": first there is a typo: "to many times" should read "too many times" I guess. And this raises the question: how many times is below "too many"? I understood that   @simonstey 's main concern is a circular chaining: c1 -> c2 -> c3 -> c1 - and I share this concern as the ODRL spec cannot stop that at the level of formal definitions. Only in the free-text part of the spec it could be said this should not be the case.
- re processing model, item 8:
-- re "... the left operand Constraint MUST be satisfied ..." again: do we want to hardwire that the result of the left operand MUST be true? Or does this operator define a temporal sequence for processing. Something like "... the left operand Constraint MUST be processed first, after its result is available the right operand Constraint MUST be processed." would fit better this purpose.
- re processing model, item 9 and 10 
-- again: this use of "unsatisfiable" mixes the result "false" of a constraint with "processing this constraint does not deliver a result" - and the latter is meant. 
-- I think the rule must be more strict and I suggest to append at the end of both item "... a warning message and the processing of the policy including this Constraint must be aborted."

**Comment by riannella** [comment]
What does C1 odrl:and C2 mean?
Both constraints must be satisfied (and we don't care when or even if they *ever* get satisfied).

So, now consider C1 odrl:isNeccessaryFor C2.
Both constraints must be satisfied and there is a temporal dependency: as soon as C1 is Satisfied, then start processing C2.

We call rename this more precisely as:
  C1 odrl:andBefore C2

We can explain that its makes sense to use with atomic constraints that have temporal characteristics.

**Comment by riannella** [comment]
How can we have "circular chaining" if there are only two operands which are both atomic constraint expressions ?

**Comment by riannella** [comment]
Item 8: If we say  "... the left operand Constraint MUST be processed first, after its result is available the right operand Constraint MUST be processed." 

Isn't the first part of that the same as saying the first constraint is satisfied? Because "the result" could be "no" and you need to wait...

**Comment by nitmws** [comment]
@riannella and @simonstey I stick to my question: is isNecessaryFor what we need or do we want to communicate: a constraint related to an Action must be checked at the time of exercising the Action.

Re Renato's thoughts above:

Re "What does C1 odrl:and C2 mean": right, both MUST be satified. And right: how to deal with "no result of C1 is available" is not discussed anywhere in the ODRL specs.

Re "C1 odrl:isNeccessaryFor C2": first: why "both MUST be satisfied", this is currently nowhere defined. Re "as soon ...": exactly that is going in the wrong direction - if the Left Operand of C1 is Count then this constraint should not be processed on 1 February, 1200 GMT and this result is used for the next 3 weeks as the count of uses will increase in this period - and that's the issue. The same applies to dynamic time values - e.g. delivered by a rightOperandReference: this should be checked at the time of executing the Action not 3 hours before that.

Re both issues above: ODRL needs a generic rule about how to deal with "while processing a Constraint expression a result cannot be generated" - this is also important for odrl:and and not only for isNecessaryFor. (Btw: in an odrl:and Constraint Relation C1 is not unnecessary for C2.) I'm aware of Simon's concern at one of the recent calls: how to define exactly "a result cannot be generated": reasons could be a resource referenced by rightOperandReference delivers an explicit error status (that's the easy variant) or the resource does not deliver any response for 15 minutes now (not so easy: should ODRL or something else define a time limit ??). And what about syntax errors: e.g. the duty to pay has a rightOperand value of "abXZ" ?

Re "circular chaining": you are right, a single Constraint Relation can combine only 2 atomic Constraints. Double check: CR1 combines C1 and C2, CR2 combines C2 and C3, CR3 combines C3 and C1: could this be considered as "circular chaining" - ? @simonstey 

Re your re Item 8: no, getting a result of a constraint is not the same as the constraint is satified. As said above how to deal with missing results is an open issue.

**Comment by riannella** [comment]
1) *All* constraints need to be checked at the time of exercising the action. So why are the Constraint Relations any different?

2) We define what happens if there is no result of a constraint in the Perm/Pro/Duty sections:
"Constraint: the Permission may refer to one or more Constraints which affect the validity of the Permission - it only becomes effective if all of the referred Constraints are true "

3) We define "satisfied" in the first para of the section: "If the logical expression evaluates to true, the result of the Constraint is satisfied."

4) "C1 odrl:isNeccessaryFor C2": first: why "both MUST be satisfied"
The both needs to be satisfied (since its also an "and" relationship)...then it goes on and says that C1 is "done" before C2 is processed.

5) If a result cannot be generated, then a result cannot be generated.
If the constraint is "event = end-of-the-world" then it won't be satisfied...ever ;-)
This is something we cannot address.

6) Syntax errors are not our problem.

**Comment by nitmws** [comment]
Re @riannella comment before:

re 1: That they _must_ be checked at the time ... is not defined. And if they _need_ to be checked at the time ... depends on the constraint: if the constraint limits the use of an asset to the time after a specific date and time one can draw conclusions from that already hours before - e.g. putting the story in a publication queue with a publication time set to the time of the constraint.
And that's exactly the goal of my proposal: to define explicitly that this constraint must be check at the time of executing the action.

re 2: sorry, this definition does not cover the issue of having no result from the referred Constraint. Where is it defined that not being able to evaluate a constraint defaults to false - and what are the conditions for "not being able"?

re 3: The definition is ok, but it does not cover the case that the logical expression cannot be evaluated. Same as in 2.

re 4: ok, item 8 of the Constraint Relations processing model can be interpreted as defining an and-relationship.

re 5 and 6: that example shows a strange/wrong design of a constraint. My concerns are about not being able to process a reasonable constraint. And with my IPTC hat on I say that e.g. the NewsML-G2 standard (for the exchange of news items) covers syntax errors and semantic errors relevant for the processing of a news item.

I can't see how this comment explains the need for isNecessaryFor or in general a rule, that one constraint must deliver a result before another constraint is processed - what use case cannot be solved without this rule? I see more need in indicating a constraint must be processed at the time of exercising an action, see my count example.

**Comment by riannella** [comment]
1/2/3 - Added a new 3rd para of the Constraint section.

4 - It is an "and" PLUS a sequence. So, we can be very precise and call it "odrl:andSequence" instead?

5/6 - The benefit you have is that IPTC covers a business domain  - with known semantics and business rules.  ODRL only has that capability in ODRL Profiles.

The use case is "a time period after an event has concluded".

**Comment by riannella** [comment]
I think this is the original requirement: https://www.w3.org/2016/poe/wiki/Requirements#POE.R.DM.06_Support_relative_time_constraints

Which turned into the big "constraints on constraints" discussion...

**Comment by riannella** [comment]
And the Use Cases: https://www.w3.org/2016/poe/wiki/Use_Cases#POE.UC.19_Relative_Time_Constraints

https://www.w3.org/2016/poe/wiki/Use_Cases#POE.UC.16_Accessing_Historical_Data

**Comment by nitmws** [comment]
Hi @riannella is this a night shift today for you :-( ?

Re your comments above: I'm aware of this discussion but my conclusion is that isNessareyFor doesn't cover the needs. Why: 
- re POE UC 19: This UC defines that first a dynamic point in time is set (end of an event) and then this point in time is the starting point for a temporal delay, only after this delay the Action may be exercised. How to design constraints for that:
-- Constraint 1: define c1 using the Action Date Time Left Operand, odrl:gteq operator and a rightOperandReference providing dynamically the end-date/time of the event. But this c1 will only deliver a result if the constraint is evaluated close to the time of the end of the event and close to the time when the action should be exercised- therefore I still think this should be explicitly indicated.
-- Constraint 2: define c2 using - hm??? - a currently not existing Delay Period Left Operand, a odrl:eq operator and a right operand of 30 minutes (for "may be used 30 minutes after the event has ended"). 
- Simple approach: combine c1 and c2 by an odrl:and as in fact both must be satified.
- The tricky thing of this design is: how to express that the starting-point-time of c2 is triggered by the 
date/time used as "end of event" in c1? A simple isNecessaryFor is not sufficient. We need an "evaluate the right operand only if the left operand constraint is satisified" relationship, named e.g. "ifSatisfiedEvaluate" (may need some pondering ...) -> c1 odrl:ifSatisfiedEvaluate c2 sounds close to the intention.
- ... and we need a Left Operand Delay Period with a definition like "A period of time after which the Action may be exercised. The start of the period is triggered if another constraint is satisfied. This other constraint and the constraint using this Left Operand must be related by an odrl:ifSatisfiedEvaluate Constraint Relation." See also: Elapsed Time Left Operand - http://w3c.github.io/poe/vocab/#term-elapsedTime
- To make this clear: using odrl:ifSatisfiedEvaluate to combine two constraints requires special Left Operands which build on this relationship.
- re POE UC 16: this UC is not very clear what may be done each month: 1 access only, or access for 1 day? Anyway: 
-- Constraint 1: define c1 using Action Date Time Left Operand with odrl:lteq operator and an explicit date/time in 7 years as right operand.
-- Constraint 2: define c2 using Recurring Time Interval Left Operand, odrl:eq operator and as right operand a period of 7 days. 
-- Constraint Relation: I think odrl:and is sufficient - as the UC does not define when the 1-month-period will start - its sound like: an exercised access triggers the period.

**Comment by riannella** [comment]
I have an AI-Bot that works at night as me ;-}

POE-UC-19 is our classic "30 Mins after then end of the football match".
C1: event gteq "http://epl.com/2017/match"
C2: dateTime gteq P30M

In this case, you can't "and" C1 and C2 as the results are not the same (C1 has to "happen" first)

The "delay period" is intrinsic in the semantics of "event".

I think that this new operator (whatever we call it) is *only* for time-based (left operand) constraints.

**Comment by nitmws** [comment]
Re POE-UC-19 ...:

- C1 Left Operand [Event](http://w3c.github.io/poe/vocab/#term-event): does not fit by its definition "_An identified **event at which** the Action may be exercised._" By that definition the right operand must be an identifier for an event - e.g. for the 2014 FIFA World Cup https://www.wikidata.org/entity/Q79859 
- C2 Left Operand [Action Date Time or Period](http://w3c.github.io/poe/vocab/#term-dateTime) is defined as "_The date (and optional time and timezone) to be compared to the time when the Action is exercised or **a period to be compared with the duration of exercising the Action**._" This definition sets as option a period **in which and not after wich** the Action may be exercised - e.g. odrl:lteq and P30M defines: for max 30 minutes. That's why I proposed the new Action Delay Period Left Operand to cover that use case.
- re "has to happen first": right, by a formal view that means that only after the event has closed C1 will deliver a "satisfied" result. And that's why I propose to have a relationship: "wait until the constraint of the left operand delivers a satisfied, only after that evaluate the right operand constraint and the point in time of receiving a "satisfied" result is a reference point in time for a temporal Left Operand of the right operand constraint" ...
- ... and I share your view that this Constraint Relation operator works only with time driven/related constraints.
- (another round of musing about its name: c1 odrl:isSatisfiedBefore c2 ?)

Could we take a step in this direction?

**Comment by riannella** [comment]
RE: "Event" semantics - you also need to account for the operator. An event is a period in time. So "lt" and "gt" are operations that can be applied to it?

The definition probably should be "An identified event used for exercising the Action"

**Comment by riannella** [comment]
Hmmm....what if you Prohibit the action, constrained with a dateTime = P30M ?

**Comment by riannella** [comment]
@nitmws Are you ok then if:
1) we change isNeccessaryFor to isSatisfiedBefore
2) add a new constraint left operand: delayPeriod

**Comment by nitmws** [comment]
@riannella I like your suggestion:

re 1: great, with a definition like "The left operand constraint of a Constraint Relation must deliver a satisfied result before the right operand constraint is evaluated. The right operand constraint may build on the satisfaction of the left operand constraint."

re 2: great too. Name = Action Delay Period, definition like "The Action may be executed after the end of this period. The starting time of the period is triggered by the satisfaction of another temporal constraint, the constraints should be related by isSatisfiedBefore."

My conclusion of the whole topic: a general "constraint on constraints" is very hard to design because there are many quite different relationships/dependencies between the constraints. isSatisfiedBefore and Action Delay Period covers only a subset of the whole topic but I think such a temporal dependency is widely used.

Personal note: next week I'm in the mountains, away from internet communication.

**Comment by nitmws** [comment]
@riannella an as I hope better naming for this discussed Constraint Relation operator has occurred to me:

- id: odrl:sequentialLtrAnd (or shorter odrl:seqLtrAnd)
- name: Sequential Left-to-Right And
- definition (as above): The left operand Constraint of a Constraint Relation must deliver a satisfied result before the right operand Constraint is evaluated. Finally both of the Constraints MUST be satisfied.  
- user note: The right operand constraint may build on the satisfaction of the left operand constraint.

The advantage of this naming is that it a/ states "this is an `and`" and b/ adds how the two operands of the `and` have to be evaluated: step by step (=sequential) from the left(Operand) to the right(Operand). I guess this makes it easier to get what this operand stands for.

**Comment by riannella** [comment]
What about: andSequence  ?

**Comment by nitmws** [comment]
We must include the direction. If C1 and C2 of the example above are in the left and right operand a sequence from right to left would spoil the intention. In this context an id `andSequenceLtr `would be ok. (And for the super-flexible people we could define an andSequenceRtl with a reversed definition ;-) )

**Comment by riannella** [comment]
Sure...but the definition makes that clear what the direction is (and left to right is natural).

It is also unlikely that we (or anyone) would then also have "andSequenceR2L" as it is the exact same as the L2R with C1 and C2 swapped ;-)

**Comment by nitmws** [comment]
My/our (bad) experience: users try to infer from the characters of an id what it stands for. I would appreciate a Ltr in the id, only 3 characters.

**Comment by riannella** [comment]
I'm not keen on putting too much semantics into the identifiers (after all, we don't use "LxorR")
